"use client";

import { useEffect, useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { SparklesIcon } from "@heroicons/react/24/outline";
import { SettingsSaveRow } from "@/components/settings/settings-save-row";
import { OfferMark } from "@/components/marks/offer-mark";
import {
  ApiError,
  generateOfferImage,
  getBrandOffer,
  isInsufficientCredit,
  renameBrandOffer,
  type Offer,
} from "@/lib/api";
import { useAuthQuery } from "@/lib/use-auth-query";

/**
 * WHAT AN OFFER IS CALLED, AND WHAT IT LOOKS LIKE.
 *
 * Neither was editable anywhere in the product. `renameBrandOffer` had shipped
 * in the api client with ZERO callers, so an offer's name was fixed at the
 * moment it was created; and every offer wore the same purple tag, so a brand
 * selling several propositions could not tell them apart in the switcher, the
 * top bar, the Offers table or the leads surfaces.
 *
 * The two belong on ONE card because they are one question — which offer is
 * this — and they are the first thing on Offer Settings for the same reason:
 * everything below it (the funnels, what it promises) is about a proposition
 * you have to be able to name first.
 *
 * ── Rules ───────────────────────────────────────────────────────────────────
 *
 * The NAME limits are brand-service's and are NOT re-implemented here: at most
 * two words, at most twenty characters, unique within the brand. Its 400/409 is
 * the answer and its sentence is what the reader sees, so a limit that moves
 * upstream moves here for free. Nothing is pre-empted client-side beyond
 * refusing to send a blank.
 *
 * The card SEEDS from the wire and RE-SEEDS when the payload changes identity —
 * a once-per-mount latch would take the on-disk snapshot the local-first cache
 * restores FIRST and ignore the server answer that lands a moment later, which
 * is the "the value saved but the screen is blank" shape. A field the user has
 * TOUCHED outranks the server: a form that rewrites itself mid-edit is worse
 * than a stale one.
 *
 * The IMAGE is generated by brand-service (chat-service owns the image cost, and
 * the org that presses the button pays for it), on the same visual template as
 * the audience avatars. A refusal is RENDERED rather than swallowed — with ONE
 * carve-out: `apiCall` already dispatches the billing-guard modal on a 402, so
 * an org that cannot afford the image gets the recharge modal and NO red line
 * under it. Two surfaces for one refusal is worse than one.
 */
export function OfferIdentityCard({ brandId, offerId }: { brandId: string; offerId: string }) {
  const queryClient = useQueryClient();

  // The offer's own row. Same key the tenant switcher's authoritative by-id read
  // uses, so opening Settings costs no second request.
  const { data, isPending, isError } = useAuthQuery(
    ["brandOffer", brandId, offerId],
    () => getBrandOffer(brandId, offerId),
    { enabled: !!brandId && !!offerId },
  );
  const offer: Offer | null = data?.offer ?? null;

  const [name, setName] = useState("");
  const [touched, setTouched] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // The payload the field was last seeded FROM, by reference. React Query returns
  // the same object when nothing changed (structural sharing), so an unchanged
  // refetch re-seeds nothing and cannot loop.
  const seededFrom = useRef<Offer | null>(null);

  useEffect(() => {
    if (!offer || offer === seededFrom.current) return;
    seededFrom.current = offer;
    if (touched) return;
    setName(offer.name);
  }, [offer, touched]);

  const writeOffer = (next: Offer) => {
    queryClient.setQueryData(["brandOffer", brandId, offerId], { offer: next });
    queryClient.invalidateQueries({ queryKey: ["brandOffers", brandId] });
  };

  const renameMut = useMutation({
    mutationFn: (value: string) => renameBrandOffer(brandId, offerId, value),
    onSuccess: (res) => {
      seededFrom.current = res.offer;
      setName(res.offer.name);
      setTouched(false);
      setSaved(true);
      setError(null);
      writeOffer(res.offer);
    },
    onError: (err) => setError(offerWriteErrorMessage(err)),
  });

  const imageMut = useMutation({
    mutationFn: () => generateOfferImage(brandId, offerId),
    onSuccess: (res) => {
      seededFrom.current = res.offer;
      setError(null);
      writeOffer(res.offer);
    },
    onError: (err) => setError(offerWriteErrorMessage(err)),
  });

  const trimmed = name.trim();
  const dirty = offer !== null && trimmed.length > 0 && trimmed !== offer.name;

  return (
    <section className="bg-white rounded-xl border border-gray-200 p-5 md:p-6">
      <h2 className="text-sm font-semibold text-gray-800">Offer identity</h2>
      <p className="mt-0.5 text-xs text-gray-500">
        What this offer is called, and the mark it wears everywhere it appears.
      </p>

      <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-start">
        {/* The mark, at the size a person judges it by — the surfaces that draw
            it render it at 18–20px, which is too small to tell two generated
            images apart while you are choosing one. */}
        <div className="flex shrink-0 items-center gap-4">
          <span className="flex items-center justify-center">
            <OfferMark size="lg" imageUrl={offer?.imageUrl} />
          </span>
          <div>
            <button
              type="button"
              onClick={() => imageMut.mutate()}
              disabled={!offer || imageMut.isPending}
              className={`inline-flex items-center gap-1.5 rounded-lg border border-brand-200 bg-brand-50 px-3 py-2 text-xs font-medium text-brand-700 transition hover:bg-brand-100 focus:outline-none focus:ring-2 focus:ring-brand-300 ${
                imageMut.isPending
                  ? "cursor-wait opacity-70"
                  : "disabled:cursor-not-allowed disabled:opacity-40"
              }`}
            >
              {imageMut.isPending ? (
                <span className="h-3 w-3 animate-spin rounded-full border-2 border-current border-t-transparent" />
              ) : (
                <SparklesIcon className="h-3.5 w-3.5" />
              )}
              {offer?.imageUrl ? "Regenerate with AI" : "Generate with AI"}
            </button>
            <p className="mt-1.5 text-xs text-gray-400">
              Drawn from this offer&apos;s name and what it promises.
            </p>
          </div>
        </div>

        <div className="min-w-0 flex-1">
          <label htmlFor="offer-name" className="block text-xs font-medium text-gray-600">
            Name
          </label>
          <input
            id="offer-name"
            type="text"
            value={name}
            onChange={(e) => {
              setName(e.target.value);
              setTouched(true);
              setSaved(false);
              setError(null);
            }}
            disabled={isPending || isError}
            placeholder={isPending ? "" : "Offer name"}
            className="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm text-gray-800 transition focus:border-brand-300 focus:outline-none focus:ring-2 focus:ring-brand-300 disabled:bg-gray-50"
          />
          <p className="mt-1.5 text-xs text-gray-400">
            At most two words and twenty characters, and different from every other offer on
            this brand. It is the only word anyone reads for this offer.
          </p>
        </div>
      </div>

      {error && <p className="mt-4 text-sm text-red-600">{error}</p>}

      <SettingsSaveRow
        dirty={dirty}
        saving={renameMut.isPending}
        saved={saved}
        onSave={() => renameMut.mutate(trimmed)}
      />
    </section>
  );
}

/**
 * A refusal from brand-service, as a sentence.
 *
 * `ApiError.message` is ALREADY the producer's own `error` field — apiCall reads
 * it out of the body — so brand-service's sentences for a person ("a name is at
 * most two words", "that name is taken") reach the reader verbatim, and a limit
 * that moves upstream moves here for free. Anything that is not an ApiError gets
 * one generic line with the real thing in the console; a raw `err.message` on a
 * network/parse failure is a stack trace in front of a customer.
 *
 * `null` means SAY NOTHING: a 402 has already opened the billing-guard modal, and
 * a red line under it would describe the same refusal twice.
 */
function offerWriteErrorMessage(err: unknown): string | null {
  console.error("[dashboard] offer identity write failed", err);
  if (isInsufficientCredit(err)) return null;
  if (err instanceof ApiError && err.message.trim()) return err.message;
  return "Could not save. Please try again.";
}
