"use client";

import Link from "next/link";
import { RevenueChart } from "@/components/revenue/revenue-chart";
import { ConversionsTabs } from "@/components/revenue/conversions-tabs";
import { RevenueCostSummary } from "@/components/revenue/revenue-cost-summary";
import { TopCampaignsCard } from "@/components/revenue/top-campaigns-card";
import { Skeleton } from "@/components/skeleton";
import type { CostByName } from "@/lib/api";
import type { RevenueOverview } from "@/lib/revenue-view";

function formatUsd(n: number | null): string {
  if (n === null) return "—";
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

/**
 * Revenue-centric overview block — expected pipeline headline, revenue-over-time
 * chart, and the Organizations / Leads / Events conversion tabs (same set as the
 * dedicated Conversions page; each table paginates 20/page). Pure render — the
 * page owns the gate + query.
 */
export function RevenueOverviewSection({
  data,
  newCampaignHref,
  costBreakdown,
  brandId,
  featureSlug,
  basePath,
  revenuePending = false,
  costPending = false,
}: {
  data?: RevenueOverview;
  newCampaignHref: string;
  costBreakdown: CostByName[];
  brandId: string;
  featureSlug: string;
  /** /orgs/:orgId/brands/:brandId/features/:slug — for the Top-campaigns links. */
  basePath: string;
  /** features-service `/revenue` reveal — headline, chart, CAC/ROI, conversions. */
  revenuePending?: boolean;
  /** runs-service cost-breakdown reveal — the Total-spent figure only. */
  costPending?: boolean;
}) {
  // Static-shell-first: the section header, card frames, titles and the tab bar
  // render on the first paint; only the data regions skeleton while loading.
  // `revenueLoading` tracks `revenuePending` ALONE — no defensive `!data` re-guard.
  // The page reveals on settle (success OR error), so on an errored `/revenue`
  // `revenuePending` is false while `data` is undefined; re-guarding on `!data` here
  // would re-lock the whole section into an eternal skeleton. Every region below is
  // null-safe (`data?.…` → "—"), so absent data renders dashes. The Total-spent
  // figure (runs-service) reveals on its own `costPending` and never waits on revenue.
  const revenueLoading = revenuePending;
  return (
    <div className="space-y-4">
      <div className="flex items-end justify-between">
        <div>
          <h2 className="font-display text-lg font-bold text-gray-800">Revenue &amp; Conversions</h2>
          <p className="text-sm text-gray-500">Expected pipeline revenue generated by this feature.</p>
        </div>
        <Link
          href={newCampaignHref}
          className="px-4 py-2 text-sm font-medium rounded-lg bg-brand-500 text-white hover:bg-brand-600 transition whitespace-nowrap"
        >
          New Campaign
        </Link>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Headline + chart */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-gray-200 p-4 md:p-6">
          <div className="flex items-baseline justify-between mb-4">
            <h3 className="font-medium text-gray-800">Pipeline revenue over time</h3>
            <div className="text-right">
              {revenueLoading ? (
                <Skeleton className="h-8 w-28" />
              ) : (
                <p className="text-2xl font-bold text-gray-900 leading-none">
                  {data ? formatUsd(data.totalPipelineUsd) : "—"}
                </p>
              )}
              <p className="text-[11px] text-gray-400 mt-1">expected pipeline</p>
            </div>
          </div>
          {revenueLoading ? (
            <Skeleton className="h-[260px] w-full rounded" />
          ) : data ? (
            <RevenueChart series={data.timeSeries} />
          ) : (
            /* Settled with no payload: say so rather than skeleton forever. The chart
               needs a series it cannot be given. */
            <p className="flex h-[260px] items-center justify-center text-sm text-gray-500">
              We could not load this right now. It will reappear on its own.
            </p>
          )}
        </div>

        {/* Cost & efficiency — spend metrics (total / cost-of-acquisition / ROI)
            with the Top-3 campaigns-by-ROI list as the bottom card (the brand-wide
            top-cost-sources list stays on the Campaigns page). */}
        <RevenueCostSummary
          costBreakdown={costBreakdown}
          costEconomics={data?.costEconomics}
          pending={revenueLoading}
          costPending={costPending}
          bottomCard={
            <TopCampaignsCard brandId={brandId} featureSlug={featureSlug} basePath={basePath} />
          }
        />
      </div>

      {/* Conversions — Organizations / Leads / Events tabs (same set as the
          dedicated Conversions page; paginated 20/page inside each table). */}
      <ConversionsTabs data={data} pending={revenueLoading} />
    </div>
  );
}
