"use client";

import Link from "next/link";
import { MaturityBadge } from "@/components/maturity-badge";
import { FEATURE_GATES } from "@/lib/feature-gates";
import { RevenueChart } from "@/components/revenue/revenue-chart";
import { OrgConversionsTable } from "@/components/revenue/conversions-table";
import type { RevenueOverview } from "@/lib/revenue-view";

function formatUsd(n: number | null): string {
  if (n === null) return "—";
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

/**
 * Revenue-centric overview block — expected pipeline headline, revenue-over-time
 * chart, and the org-level conversion table (deduped "lead organisation" rows;
 * the Events tab lives on the dedicated Conversions page). Pure render — the page
 * owns the gate + query.
 */
export function RevenueOverviewSection({
  data,
  conversionsHref,
}: {
  data: RevenueOverview;
  conversionsHref: string;
}) {
  return (
    <div className="space-y-4">
      <div className="flex items-end justify-between">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="font-display text-lg font-bold text-gray-800">Revenue &amp; Conversions</h2>
            <MaturityBadge level={FEATURE_GATES["conversions"].maturity} />
          </div>
          <p className="text-sm text-gray-500">Expected pipeline revenue generated by this feature.</p>
        </div>
        <Link href={conversionsHref} className="text-xs font-medium text-brand-600 hover:text-brand-700 whitespace-nowrap">
          View all conversions →
        </Link>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Headline + chart */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-gray-200 p-4 md:p-6">
          <div className="flex items-baseline justify-between mb-4">
            <h3 className="font-medium text-gray-800">Pipeline revenue over time</h3>
            <div className="text-right">
              <p className="text-2xl font-bold text-gray-900 leading-none">
                {formatUsd(data.totalPipelineUsd)}
              </p>
              <p className="text-[11px] text-gray-400 mt-1">expected pipeline</p>
            </div>
          </div>
          <RevenueChart series={data.timeSeries} />
        </div>

        {/* Quick stats */}
        <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-1 gap-4">
          <div className="bg-white rounded-xl border border-gray-200 p-4">
            <p className="text-xs text-gray-400">Converting organizations</p>
            <p className="mt-1 text-xl font-bold text-gray-900">{data.organizations.length}</p>
          </div>
          <div className="bg-white rounded-xl border border-gray-200 p-4">
            <p className="text-xs text-gray-400">Lead conversions</p>
            <p className="mt-1 text-xl font-bold text-gray-900">{data.leads.length}</p>
          </div>
          <div className="bg-white rounded-xl border border-gray-200 p-4">
            <p className="text-xs text-gray-400">Conversion events</p>
            <p className="mt-1 text-xl font-bold text-gray-900">{data.events.length}</p>
          </div>
        </div>
      </div>

      {/* Org-level conversions (overview shows organisations only). */}
      <OrgConversionsTable orgs={data.organizations} />
    </div>
  );
}
