"use client";

import type { ReactNode } from "react";
import { RevenueChart } from "@/components/revenue/revenue-chart";
import { ConversionsTabs } from "@/components/revenue/conversions-tabs";
import { RevenueCostSummary } from "@/components/revenue/revenue-cost-summary";
import { TopCampaignsCard } from "@/components/revenue/top-campaigns-card";
import { Skeleton } from "@/components/skeleton";
import type { CostByName } from "@/lib/api";
import type { RevenueOverview } from "@/lib/revenue-view";

function formatUsd(n: number | null): string {
  if (n === null) return "—";
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

/**
 * Revenue-centric overview block — expected pipeline headline, revenue-over-time
 * chart, and the Organizations / Leads / Events conversion tabs (same set as the
 * dedicated Conversions page; each table paginates 20/page). Pure render — the
 * page owns the gate + query.
 */
export function RevenueOverviewSection({
  data,
  costBreakdown,
  brandId,
  featureSlug,
  basePath,
  topRow,
  revenuePending = false,
  costPending = false,
  hideHeader = false,
  conversions,
}: {
  data?: RevenueOverview;
  costBreakdown: CostByName[];
  brandId: string;
  featureSlug: string;
  /** /orgs/:orgId/brands/:brandId/features/:slug — for the Top-campaigns links. */
  basePath: string;
  /** Optional row rendered under the header, above the Pipeline-revenue hero. */
  topRow?: ReactNode;
  /** features-service `/revenue` reveal — headline, chart, CAC/ROI, conversions. */
  revenuePending?: boolean;
  /** runs-service cost-breakdown reveal — the Total-spent figure only. */
  costPending?: boolean;
  /** Hide the "Revenue & Conversions" header (the Signups page provides its own
   *  header + Run Campaign action). */
  hideHeader?: boolean;
  /** Replace the default Organizations/Leads conversion tabs (the Signups page
   *  supplies its own engaged-leads table: opened / clicked / signed up). */
  conversions?: ReactNode;
}) {
  // Static-shell-first: the section header, card frames, titles and the tab bar
  // render on the first paint; only the data regions skeleton while loading.
  // `revenueLoading` folds `revenuePending` with a defensive `!data` guard — it
  // drives every region fed by features-service `/revenue`; the Total-spent figure
  // (runs-service) reveals on its own `costPending` so it never waits on revenue.
  const revenueLoading = revenuePending || !data;
  return (
    <div className="space-y-4">
      {!hideHeader && (
        <div>
          <h2 className="font-display text-lg font-bold text-gray-800">Revenue &amp; Conversions</h2>
          <p className="text-sm text-gray-500">Expected pipeline revenue generated by this feature.</p>
        </div>
      )}

      {topRow}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Headline + chart */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-gray-200 p-4 md:p-6">
          <div className="flex items-baseline justify-between mb-4">
            <h3 className="font-medium text-gray-800">Pipeline revenue over time</h3>
            <div className="text-right">
              {revenueLoading ? (
                <Skeleton className="h-8 w-28" />
              ) : (
                <p className="text-2xl font-bold text-gray-900 leading-none">
                  {formatUsd(data.totalPipelineUsd)}
                </p>
              )}
              <p className="text-[11px] text-gray-400 mt-1">expected pipeline</p>
            </div>
          </div>
          {revenueLoading ? (
            <Skeleton className="h-[260px] w-full rounded" />
          ) : (
            <RevenueChart series={data.timeSeries} />
          )}
        </div>

        {/* Cost & efficiency — spend metrics (total / cost-of-acquisition / ROI)
            with the Top-3 campaigns-by-ROI list as the bottom card (the brand-wide
            top-cost-sources list stays on the Campaigns page). */}
        <RevenueCostSummary
          costBreakdown={costBreakdown}
          costEconomics={data?.costEconomics}
          pending={revenueLoading}
          costPending={costPending}
          bottomCard={
            <TopCampaignsCard brandId={brandId} featureSlug={featureSlug} basePath={basePath} />
          }
        />
      </div>

      {/* Conversions — the default Organizations / Leads tabs, OR a caller-
          supplied replacement (the Signups page passes its own engaged-leads
          table: opened / clicked / signed up). */}
      {conversions ?? <ConversionsTabs data={data} pending={revenueLoading} />}
    </div>
  );
}
