export const URLS = {
  landing: "https://distribute.you",
  dashboard: "https://dashboard.distribute.you",
  docs: "https://docs.distribute.you",
  salesLanding: "https://salescoldemail.distribute.you",
  api: "https://api.distribute.you",
  apiDocs: "https://api.distribute.you/docs",
  mcp: "https://mcp.distribute.you/mcp",
  github: "https://github.com/shamanic-technologies/distribute.you",
  twitter: "https://twitter.com/distribute_you",
  signUp: "https://dashboard.distribute.you/sign-up",
  signIn: "https://dashboard.distribute.you/sign-in",
  apiKeys: "https://dashboard.distribute.you/api-keys",
  performance: "https://performance.distribute.you",
} as const;
