"use client";

import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { useAuthQuery } from "@/lib/use-auth-query";
import { isRevenueFeature } from "@/lib/revenue-feature";
import { getFeatureRevenue } from "@/lib/api";
import { RevenueChart } from "@/components/revenue/revenue-chart";
import {
  OrgConversionsTable,
  LeadConversionsTable,
  EventConversionsTable,
} from "@/components/revenue/conversions-table";
import { RevenueEmptyState } from "@/components/revenue/revenue-empty-state";
import { Skeleton } from "@/components/skeleton";

type Tab = "organizations" | "leads" | "events";

const TABS: { id: Tab; label: string }[] = [
  { id: "organizations", label: "Organizations" },
  { id: "leads", label: "Leads" },
  { id: "events", label: "Events" },
];

function formatUsd(n: number | null): string {
  if (n === null) return "—";
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

export default function ConversionsPage() {
  const params = useParams();
  const orgId = params.orgId as string;
  const brandId = params.brandId as string;
  const featureSlug = params.featureSlug as string;
  const enabled = isRevenueFeature(featureSlug);

  const [tab, setTab] = useState<Tab>("organizations");
  const { data, isPending } = useAuthQuery(
    ["featureRevenue", brandId, featureSlug],
    () => getFeatureRevenue(featureSlug, brandId),
    { enabled },
  );

  // Join each event's leadId → the lead's profile photo (both on this same
  // /revenue payload) so the Events table shows pictures, not just initials.
  const photoByLeadId = useMemo(
    () => new Map((data?.leads ?? []).map((l) => [l.leadId, l.photoUrl] as const)),
    [data?.leads],
  );

  if (!isRevenueFeature(featureSlug)) {
    return (
      <div className="p-4 md:p-8 max-w-7xl mx-auto">
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center text-sm text-gray-400">
          This view isn&apos;t available yet.
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-xl font-semibold text-gray-900">Revenue &amp; Conversions</h1>
        <p className="text-sm text-gray-500 mt-1">
          Expected pipeline revenue generated by {featureSlug.replace(/-/g, " ")}, attributed per
          organization and lead.
        </p>
      </div>

      {isPending || !data ? (
        <div className="space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[0, 1, 2].map((i) => (
              <Skeleton key={i} className="h-24 w-full rounded-xl" />
            ))}
          </div>
          <Skeleton className="h-[320px] w-full rounded-xl" />
          <Skeleton className="h-64 w-full rounded-xl" />
        </div>
      ) : data.totalPipelineUsd === null ? (
        <RevenueEmptyState
          setupHref={`/orgs/${orgId}/brands/${brandId}/features/${featureSlug}/campaigns/new`}
        />
      ) : (
        <>
          {/* Stat cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
              <p className="text-xs text-gray-400">Expected pipeline revenue</p>
              <p className="mt-1 text-2xl font-bold text-gray-900">{formatUsd(data.totalPipelineUsd)}</p>
            </div>
            <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
              <p className="text-xs text-gray-400">Converting organizations</p>
              <p className="mt-1 text-2xl font-bold text-gray-900">{data.organizations.length}</p>
            </div>
            <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
              <p className="text-xs text-gray-400">Conversion events</p>
              <p className="mt-1 text-2xl font-bold text-gray-900">{data.events.length}</p>
            </div>
          </div>

          {/* Revenue over time */}
          <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
            <h3 className="font-medium text-gray-800 mb-4">Pipeline revenue over time</h3>
            <RevenueChart series={data.timeSeries} />
          </div>

          {/* Conversions tables with tabs */}
          <div className="space-y-4">
            <div className="inline-flex items-center gap-1 bg-gray-50 border border-gray-200 rounded-lg p-1">
              {TABS.map((t) => (
                <button
                  key={t.id}
                  type="button"
                  onClick={() => setTab(t.id)}
                  className={`px-3 py-1.5 text-xs font-medium rounded-md transition ${
                    tab === t.id
                      ? "bg-brand-50 text-brand-700 border border-brand-200"
                      : "text-gray-500 hover:text-gray-800"
                  }`}
                >
                  {t.label}
                </button>
              ))}
            </div>

            {tab === "organizations" && <OrgConversionsTable orgs={data.organizations} />}
            {tab === "leads" && <LeadConversionsTable leads={data.leads} />}
            {tab === "events" && (
              <EventConversionsTable events={data.events} photoByLeadId={photoByLeadId} />
            )}
          </div>
        </>
      )}
    </div>
  );
}
