"use client";

import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { useFeatureFlag } from "@/lib/use-feature-flag";
import { FEATURE_GATES } from "@/lib/feature-gates";
import { MaturityBadge } from "@/components/maturity-badge";
import { RevenueChart } from "@/components/revenue/revenue-chart";
import {
  OrgConversionsTable,
  LeadConversionsTable,
  EventConversionsTable,
} from "@/components/revenue/conversions-table";
import { sampleRevenueOverview } from "@/lib/revenue-sample";

type Tab = "organizations" | "leads" | "events";

const TABS: { id: Tab; label: string }[] = [
  { id: "organizations", label: "Organizations" },
  { id: "leads", label: "Leads" },
  { id: "events", label: "Events" },
];

function formatUsd(n: number): string {
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

export default function ConversionsPage() {
  const params = useParams();
  const featureSlug = params.featureSlug as string;
  const ok = useFeatureFlag(FEATURE_GATES["conversions"].flag);

  const [tab, setTab] = useState<Tab>("organizations");
  // TEMP: sample data driven through the revenue calc lib. Swap for an adapter over
  // features-service GET /v1/features/{slug}/revenue once that endpoint deploys.
  const data = useMemo(() => sampleRevenueOverview(), []);

  if (!ok) {
    return (
      <div className="p-4 md:p-8 max-w-7xl mx-auto">
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center text-sm text-gray-400">
          This view isn&apos;t available yet.
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2">
          <h1 className="text-xl font-semibold text-gray-900">Revenue &amp; Conversions</h1>
          <MaturityBadge level={FEATURE_GATES["conversions"].maturity} />
        </div>
        <p className="text-sm text-gray-500 mt-1">
          Expected pipeline revenue generated by {featureSlug.replace(/-/g, " ")}, attributed per
          organization and lead.
        </p>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
          <p className="text-xs text-gray-400">Expected pipeline revenue</p>
          <p className="mt-1 text-2xl font-bold text-gray-900">
            {formatUsd(data.totalPipelineUsd)}
          </p>
          {data.undatedPipelineUsd > 0 && (
            <p className="mt-1 text-[11px] text-gray-400">
              incl. {formatUsd(data.undatedPipelineUsd)} not yet dated
            </p>
          )}
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
          <p className="text-xs text-gray-400">Converting organizations</p>
          <p className="mt-1 text-2xl font-bold text-gray-900">{data.orgs.length}</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
          <p className="text-xs text-gray-400">Conversion events</p>
          <p className="mt-1 text-2xl font-bold text-gray-900">{data.events.length}</p>
        </div>
      </div>

      {/* Revenue over time */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 md:p-6">
        <h3 className="font-medium text-gray-800 mb-4">Pipeline revenue over time</h3>
        <RevenueChart series={data.series} />
      </div>

      {/* Conversions tables with tabs */}
      <div className="space-y-4">
        <div className="inline-flex items-center gap-1 bg-gray-50 border border-gray-200 rounded-lg p-1">
          {TABS.map((t) => (
            <button
              key={t.id}
              type="button"
              onClick={() => setTab(t.id)}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition ${
                tab === t.id
                  ? "bg-brand-50 text-brand-700 border border-brand-200"
                  : "text-gray-500 hover:text-gray-800"
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {tab === "organizations" && <OrgConversionsTable orgs={data.orgs} />}
        {tab === "leads" && <LeadConversionsTable leads={data.leads} />}
        {tab === "events" && <EventConversionsTable events={data.events} />}
      </div>
    </div>
  );
}
